# Simple numpy neural network

Stepik neural networks steps 3.3.2 - 3.3.4

The weights in the example are already given, therefore we do not need addionally initialize them 

In [1]:
import numpy as np

In [76]:
class NeuronNetwork:
    def __init__(self, weights):
        self.weights = weights
        self.activation_values = []

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(self, activation_value):
        return activation_value * (1 - activation_value)

    def predict(self, a):
        for i in range(len(self.weights)):
            z = self.weights[i].T.dot(a)
            a = self.sigmoid(z)
            self.activation_values.append(a)
        return a

    def J_quadratic(self, X, y):
        assert y.shape[1] == 1, 'Incorrect y shape'

        return 0.5 * np.mean((self.predict(X) - y) ** 2)

    def grad(self, y_hat, y):
        assert y_hat.shape == y.shape and y_hat.shape[1] == 1, 'Incorrect shapes'

        return y_hat - y

    def train(self, X, y):
        a_L = self.predict(X)
        nabla_j = self.grad(a_L, y)
        #print(nabla_j)
        delta_l = nabla_j * self.sigmoid_derivative(a_L)
        print(a_L)

        for i in range(len(self.activation_values) - 2, -1, -1):
            delta_l = self.weights[i+1].dot(delta_l)
            delta_l = delta_l * self.sigmoid_derivative(self.activation_values[i])
            print(delta_l)


### 3.3.2

In [77]:
weights = [
    np.array([[2, 2], [2, 2], [2, 2]]),
    np.array([[1], [1]])
]

network = NeuronNetwork(weights)
res = network.train(np.array([[0], [1], [2]]), np.array([[1]]))

[[ 0.88027688]]
[[ -3.11213266e-05]
 [ -3.11213266e-05]]


### 3.3.3

In [78]:
weights = [
    np.array([[8, 10], [7, 10], [8, 9]]),
    np.array([[10], [9]])
]

network = NeuronNetwork(weights)
res = network.train(np.array([[0], [1], [2]]), np.array([[1]]))

[[ 0.99999999]]
[[ -3.22134047e-26]
 [ -1.95348927e-28]]


### 3.3.4

In [79]:
weights = [
    np.array([[0.2, 0.2], [0.9, 0.3], [0.6, 0.7]]),
    np.array([[0.2], [0.5]])
]

network = NeuronNetwork(weights)
res = network.train(np.array([[15], [5], [15]]), np.array([[1]]))

[[ 0.66818774]]
[[ -1.00427894e-09]
 [ -1.12521595e-08]]
