In [19]:
y_hat = np.array([1, 0.3, 0.1])
y = np.array([1, 1e-5, 1e-5])
eps = 1e-5

In [16]:
y[y==0]=eps


In [20]:
y

array([  1.00000000e+00,   1.00000000e-05,   1.00000000e-05])

In [22]:
-1/len(y)*(y*np.log(y_hat) + (1-y)*np.log(1-y_hat))

/Users/lizzzi111/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  
/Users/lizzzi111/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in multiply
  


array([        nan,  0.11889447,  0.0351275 ])

In [13]:

np.log(y)

/Users/lizzzi111/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([  0., -inf, -inf])

In [25]:
one_ = y*np.log(y_hat)

In [26]:
two_= (1-y)*np.log(1-y_hat)

/Users/lizzzi111/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.
/Users/lizzzi111/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in multiply
  """Entry point for launching an IPython kernel.


In [28]:
two_[0] = eps

In [31]:
-1/len(y)*(one_+two_).sum()

0.15401863494031198